### ISSUE TITLE
[Question] A little question about %r15~%r12, %rbx usage

### ISSUE THREAD

**Issue by WindSoilder** [cfsamson/example-greenthreads#18]
Would you please tell me what *%r15 ~ %12, %rbx* do in the `switch` function and `ThreadContext` in the [implementation](https://cfsamson.gitbook.io/green-threads-explained-in-200-lines-of-rust/simple-but-unsafe-green-thread-implementation)?

I have tried to removed them and make them something like this:
```rust
#[naked]
#[inline(never)]
unsafe fn switch(old: *mut ThreadContext, new: *const ThreadContext) {
    llvm_asm!("
        mov %rsp, 0x00($0)
        mov %rbp, 0x08($0)

        mov 0x00($1), %rsp
        mov 0x08($1), %rbp
        ret
    "
        :
        :"r"(old), "r"(new)
        :
        : "volatile", "alignstack"
    )
}

#[derive(Debug, Default)]
#[repr(C)]
struct ThreadContext {
    rsp: u64,
    rbp: u64,
}
```
It still works..

**Comment by cfsamson** [comment]
`r12` - `r15` are callee saved registers specified in the System V ABI as you can see in the chart in [chapter 3](https://cfsamson.gitbook.io/green-threads-explained-in-200-lines-of-rust/background-information). If you want to read more about it you can take a look [here](https://cfsamson.gitbook.io/green-threads-explained-in-200-lines-of-rust/background-information).

Callee saved means that the calling convention expects these registers to be preserved across function calls and it's therefore the callee's responsibility to save them and restore them before returning. 

In our stack-jumping example this means that functions on "stack a" might hold long-lived values in these registers and rely on them, so if we don't restore them after running instructions using "stack b" some programs will break.

**Comment by WindSoilder** [comment]
Thanks, got it
