### ISSUE TITLE
Example thread context is never used

### ISSUE THREAD

**Issue by HeyZoos** [cfsamson/example-greenthreads#3]
In the code snippet [here](https://cfsamson.gitbook.io/green-threads-explained-in-200-lines-of-rust/an-example-we-can-build-upon#running-our-example)

```rust
fn main() {
    let mut ctx = ThreadContext::default();
    let mut n = ThreadContext::default();

    let mut stack = vec![0_u8; SSIZE as usize];
    let stack_ptr = stack.as_mut_ptr();

    unsafe {
        std::ptr::write(stack_ptr.offset(SSIZE - 16) as *mut u64, hello as u64);
        ctx.rsp = stack_ptr.offset(SSIZE - 16) as u64;
        gt_switch(&mut ctx, &mut n);
    }
}
```

A mutable reference `n` to a `ThreadContext` is created that is passed as an argument to `gt_switch`. However, the signature of `gt_switch` is defined as:

```rust
gt_switch(new: *const ThreadContext)
```

This second context is also not found in the [final result](https://gist.github.com/cfsamson/4b10bd4e1e828f71405418513cc5b880)

**Comment by cfsamson** [comment]
Thanks for spotting this. I got a comment about this on reddit and thought it was fixed but the merge failed. It's corrected now.
