### ISSUE TITLE
Typos in book

### ISSUE THREAD

**Issue by jrconlin** [cfsamson/example-greenthreads#4]
Thanks for the article. It's very well presented, but there are a few minor typos.

Not sure how to file a PR to fix, so if you don't mind, here are the ones I've found.

https://cfsamson.gitbook.io/green-threads-explained-in-200-lines-of-rust/background-information

> the CPU directly we need ~a~ some minimal code written in Assembly

https://cfsamson.gitbook.io/green-threads-explained-in-200-lines-of-rust/an-example-we-can-build-upon

> we don't pass the value of the `u64` store~a~d at that location

https://cfsamson.gitbook.io/green-threads-explained-in-200-lines-of-rust/simple-but-unsafe-green-thread-implementation

>~Lets~ Let's move on:

> As ~i~ I warned before

> Our threads alternate~s~ since

**Comment by bernardosulzbach** [comment]
I was also looking for a way to submit a PR like @jrconlin for the book text itself. The thing is called a **Git**Book, but it doesn't seem all that open.

**Comment by cfsamson** [comment]
Hi and thanks for the corrections. I'll correct these right now. The repo for the book itself is located at: [https://github.com/cfsamson/book-green-threads-explained](https://github.com/cfsamson/book-green-threads-explained) so it should be possible to correct there.

**Comment by jrconlin** [comment]
Thanks! Would it be easier for you if I submitted a PR for the corrections?

**Comment by cfsamson** [comment]
No problem :) I actually corrected them right now, but Gibook is giving me some issues right now so it might take some time before it's updated. If you spot any more it's just a few clicks for me to merge them in the repo so that would be lovely. Anyway, thanks for the corrections :)

**Comment by cfsamson** [comment]
The issue with Gitbook seems to be resolved now so all the typos here seems to be fixed.

**Comment by bernardosulzbach** [comment]
> Hi and thanks for the corrections. I'll correct these right now. The repo for the book itself is located at: https://github.com/cfsamson/book-green-threads-explained so it should be possible to correct there.

Well, I should have searched harder then. Good to know where it is.

Thank you for the book.

**Comment by cfsamson** [comment]
No problem. Thanks for reading and suggesting improvements!
